# Generated by Django 4.2.6 on 2023-12-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="role",
            field=models.CharField(
                choices=[("writer", "writer"), ("moderator", "moderator")],
                max_length=10,
                null=True,
            ),
        ),
    ]
